### ISSUE TITLE
can't install on Drupal 8 with separate databases

### ISSUE THREAD

**Issue by johncronan** [veda-consulting/uk.co.vedaconsulting.mailchimp#310]
When I tried to install on Drupal 8 + CiviCRM 5.10 beta1, I got the following error message on screen:

`SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "drupal_webform_component" does not exist LINE 1: SELECT * FROM drupal_webform_component WHERE type ='fieldset... ^: SELECT * FROM {webform_component} WHERE type ='fieldset' AND form_key LIKE '%cg1_fieldset'; Array ( )`

There doesn't appear to be anything in the log file. Possibly this is related to using a separate database for CiviCRM than my CMS (which is Postgres). I heard that this can be problematic.

**Comment by johncronan** [comment]
This happens right after download. If I go on anyway, and click "install," I see the following in the log:

```
Jan 21 11:46:35  [info]
$Fatal Error Details = <pre class='xdebug-var-dump' dir='ltr'>
<small>/var/www/dev.acreresidency.org/vendor/civicrm/civicrm-core/CRM/Core/Error
.php:563:</small>
<b>array</b> <i>(size=3)</i>
  'message' <font color='#888a85'>=&gt;</font> <small>string</small> <font color
='#cc0000'>'; is not supported in SQL strings. Use only one statement at a time.
'</font> <i>(length=68)</i>
  'code' <font color='#888a85'>=&gt;</font> <font color='#3465a4'>null</font>
  'exception' <font color='#888a85'>=&gt;</font>
    <b>object</b>(<i>CiviCRM_API3_Exception</i>)[<i>964</i>]
      <i>private</i> 'extraParams' <font color='#888a85'>=&gt;</font>
        <b>array</b> <i>(size=3)</i>
          'is_error' <font color='#888a85'>=&gt;</font> <small>int</small> <font color='#4e9a06'>1</font>
          'error_message' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'; is not supported in SQL strings. Use only one statement at a time.'</font> <i>(length=68)</i>
          'error_code' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'undefined'</font> <i>(length=9)</i>
      <i>protected</i> 'message' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'; is not supported in SQL strings. Use only one statement at a time.'</font> <i>(length=68)</i>
      <i>private</i> 'string' <small>(Exception)</small> <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>''</font> <i>(length=0)</i>
      <i>protected</i> 'code' <font color='#888a85'>=&gt;</font> <small>int</small> <font color='#4e9a06'>0</font>
      <i>protected</i> 'file' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'/var/www/dev.acreresidency.org/vendor/civicrm/civicrm-core/api/api.php'</font> <i>(length=70)</i>
      <i>protected</i> 'line' <font color='#888a85'>=&gt;</font> <small>int</small> <font color='#4e9a06'>45</font>
      <i>private</i> 'trace' <small>(Exception)</small> <font color='#888a85'>=&gt;</font>
        <b>array</b> <i>(size=31)</i>
          0 <font color='#888a85'>=&gt;</font>
            <b>array</b> <i>(size=4)</i>
              ...
          1 <font color='#888a85'>=&gt;</font>
            <b>array</b> <i>(size=6)</i>
              ...
          2 <font color='#888a85'>=&gt;</font>
            <b>array</b> <i>(size=6)</i>
              ...
          3 <font color='#888a85'>=&gt;</font>
            <b>array</b> <i>(size=6)</i>
              ...
          4 <font color='#888a85'>=&gt;</font>
            <b>array</b> <i>(size=6)</i>
              ...
          5 <font color='#888a85'>=&gt;</font>
            <b>array</b> <i>(size=6)</i>
              ...
          6 <font color='#888a85'>=&gt;</font>
            <b>array</b> <i>(size=6)</i>
              ...
          7 <font color='#888a85'>=&gt;</font>
            <b>array</b> <i>(size=6)</i>
              ...
          8 <font color='#888a85'>=&gt;</font>
            <b>array</b> <i>(size=6)</i>
              ...
          9 <font color='#888a85'>=&gt;</font>
            <b>array</b> <i>(size=6)</i>
              ...
          10 <font color='#888a85'>=&gt;</font>
            <b>array</b> <i>(size=6)</i>
              ...
...
          30 <font color='#888a85'>=&gt;</font>
            <b>array</b> <i>(size=6)</i>
              ...
      <i>private</i> 'previous' <small>(Exception)</small> <font color='#888a85'>=&gt;</font> <font color='#3465a4'>null</font>
      <i>public</i> 'xdebug_message' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'&lt;tr&gt;&lt;th align=&#39;left&#39; bgcolor=&#39;#f57900&#39; colspan=&quot;5&quot;&gt;&lt;span style=&#39;background-color: #cc0000; color: #fce94f; font-size: x-large;&#39;&gt;( ! )&lt;/span&gt; CiviCRM_API3_Exception: ; is not supported in SQL strings. Use only one statement at a time. in /var/www/dev.acreresidency.org/vendor/civicrm/civicrm-core/api/api.php on line &lt;i&gt;45&lt;/i&gt;&lt;/th&gt;&lt;/tr&gt;&#10;&lt;tr&gt;&lt;th align=&#39;left&#39; bgcolor=&#39;#e9b96e&#39; colspan=&#39;5&#39;&gt;Call Stack&lt;/th&gt;&lt;/tr&gt;&#10;&lt;tr&gt;&lt;th align=&#39;center&#39; bgcolor=&#39;#eeeeec&#39;&gt;#&lt;/th&gt;&lt;th align=&#39;left&#39; bgcolor=&#39;#eeeeec&#39;&gt;Time&lt;/th&gt;&lt;th align=&#39;le'...</font> <i>(length=13033)</i>
</pre>

Jan 21 11:46:35  [info] $backTrace = #0 /var/www/dev.acreresidency.org/vendor/civicrm/civicrm-core/CRM/Core/Error.php(459): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /var/www/dev.acreresidency.org/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php(55): CRM_Core_Error::handleUnhandledException(Object(CiviCRM_API3_Exception))
#2 /var/www/dev.acreresidency.org/web/modules/contrib/civicrm/src/Civicrm.php(88): CRM_Core_Invoke::invoke((Array:3))
#3 /var/www/dev.acreresidency.org/web/modules/contrib/civicrm/src/Controller/CivicrmController.php(75): Drupal\civicrm\Civicrm->invoke((Array:3))
#4 [internal function](): Drupal\civicrm\Controller\CivicrmController->main((Array:3), "")
#5 /var/www/dev.acreresidency.org/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array((Array:2), (Array:2))
#6 /var/www/dev.acreresidency.org/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#7 /var/www/dev.acreresidency.org/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#8 /var/www/dev.acreresidency.org/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext((Array:2), (Array:2))
#9 /var/www/dev.acreresidency.org/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#10 /var/www/dev.acreresidency.org/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#11 /var/www/dev.acreresidency.org/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#12 /var/www/dev.acreresidency.org/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#13 /var/www/dev.acreresidency.org/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#14 /var/www/dev.acreresidency.org/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#15 /var/www/dev.acreresidency.org/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#16 /var/www/dev.acreresidency.org/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#17 /var/www/dev.acreresidency.org/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#18 /var/www/dev.acreresidency.org/web/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#19 /var/www/dev.acreresidency.org/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#20 {main}
```

**Comment by johncronan** [comment]
I tried installing again, and I get a different problem, now. So I'm going to close this.
